image: python:3.5

pipelines:
    default:
        - step:
            script:
                - pip install -U tox
                - tox -e py35
        - step:
            image: python:2.7
            script:
                - pip install -U tox
                - tox -e py27
    tags:
        '*':
            - step:
                script:
                    - pip install -U tox wheel
                    - tox -e py35
                    - ./deploy.bash
