image: python:3.5.1

pipelines:
    default:
        - step:
            script:
                - pip install -U tox wheel
                - tox -e py35
                - ./deploy.bash
    tags:
        '*':
            - step:
                script:
                    - pip install -U tox wheel
                    - tox -e py35
                    - ./deploy.bash
