image: python:3.5.1

pipelines:
    default:
        - step:
            script:
                - pip install -U tox
                - tox -e py35
                - echo $(pwd)
                - ./deploy.bash
    tags:
        '*':
            - step:
                script:
                    - pip install -U tox
                    - tox -e py35
                    - echo $(pwd)
                    - ./deploy.bash
